- name: install package
  yum: name={{ item }}
  with_items:
  - keepalived
- name: copy master_keepalived.conf.j2 to MASTER node
  when: ansible_hostname == "s061"
  template: src=master_keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify: reload server

- name: copy backup_keepalived.conf.j2 to BACKUP node
  when: ansible_hostname == "s062"
  template: src=backup_keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify: reload server

- name: copy notice
  template: src={{item.src}} dest={{item.dest}} owner=root group=root mode=0755
  with_items: 
    - {src: check_ng.sh.j2,dest: /usr/local/sbin/check_ng.sh}
    - {src: notify.sh.j2,dest: /usr/local/sbin/notify.sh}

- name: start server
  service: name={{ item }} state=restarted enabled=true
  with_items:
  - keepalived
