#- name: Copy Nginx bin
#  copy: src=sbin_nginx dest=/usr/sbin/ owner=root group=root mode=0755
- name: Uncompression Nginx Software
  unarchive: src=nginx.tar.gz dest=/usr/local/ owner=nginx group=nginx mode=0755
#- name: Uncompression Nginx conf
#  unarchive: src=nginx_conf.tar.gz dest=/etc/ owner=root group=root mode=0755
- name: nginx conf copy
  copy: src={{item.src}} dest={{item.dest}} owner=root group=root mode=0755
  with_items:
    - {src: sbin_nginx,dest: /usr/sbin/nginx}
#    - {src: init.d_nginx,dest: /etc/init.d/nginx}
    - {src: nginx,dest: /etc/}
- name: mkdir dir
  file: path={{item}} state=directory owner=nginx group=root mode=0755
  with_items:
    - /var/nginx/proxy_temp_dir
    - /var/log/nginx/
    - /tmp/nginx/client_body
    - /data/www
    - /data/www/default
- name: Copy nginx.conf to /etc/nginx/
  template: src={{item.src}} dest={{item.dest}} owner=nginx group=root mode=0755
  with_items: 
    - {src: init.d_nginx,dest: /etc/init.d/nginx}
    - {src: nginx.conf,dest: /etc/nginx/nginx.conf}
    - {src: index.html.j2,dest: /data/www/default/index.html}
    - {src: tanzhen.php.j2,dest: /data/www/default/tanzhen.php}
- name: start nginx(sytemctl)
  when: ansible_distribution_major_version == "7"
  systemd:
    name: nginx
    state: started
    daemon_reload: yes
- name: config nginx.service start up on boot
  when: ansible_distribution_major_version == "7"
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes  
